### ISSUE TITLE
Crashed on Android 6.0 using sdk 2.1.6.

### ISSUE THREAD

**Issue by MushoodMunir** [appcelerator-modules/ti.admob#50]
I am using admob sdk 2.1.6, titanium sdk 5.1.2 and building for Android 6.0. App crashed straight away with following crash log when using admob.

[ERROR] :  TiApplication: (main) [12,2164] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzan;; Titanium 5.1.2,2015/12/16 19:00,ca822b2
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzan;
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zze.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zzcO(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
[ERROR] :  TiApplication: 	at ti.admob.View$2.run(View.java:81)
[ERROR] :  TiApplication: 	at android.app.Activity.runOnUiThread(Activity.java:5511)
[ERROR] :  TiApplication: 	at ti.admob.View.loadAd(View.java:69)
[ERROR] :  TiApplication: 	at ti.admob.View.createAdView(View.java:64)
[ERROR] :  TiApplication: 	at ti.admob.View.processProperties(View.java:135)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:505)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at dk.napp.drawer.Drawer.processProperties(Drawer.java:365)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)
[ERROR] :  TiApplication: 	at dk.napp.drawer.DrawerProxy.windowCreated(DrawerProxy.java:146)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:508)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:601)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:6237)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[INFO] :   Application: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] :  TiApplication: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzan" on path: DexPathList[[zip file "/data/app/com.adaminoor.RotoBaller2014-1/base.apk"],nativeLibraryDirectories=[/data/app/com.adaminoor.RotoBaller2014-1/lib/x86, /data/app/com.adaminoor.RotoBaller2014-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
[ERROR] :  TiApplication: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[ERROR] :  TiApplication: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[ERROR] :  TiApplication: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[ERROR] :  TiApplication: 	... 43 more
[ERROR] :  TiApplication: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzan
[ERROR] :  TiApplication: 		at java.lang.Class.classForName(Native Method)
[ERROR] :  TiApplication: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[ERROR] :  TiApplication: 		at java.lang.BootClassL
[WARN] :   TiVerify: (Timer-0) [2835,4999] Verifying module licenses...

I also tried to build for android 5.1.0 but same result. Someone look into this.

**Comment by deckameron** [comment]
@MushoodMunir It seems this module has been abandoned...

**Comment by imlordeyaya** [comment]
Hello, I have similar problem. App without admob works, when I add this module it crashes on Android 6.0. I have tried it in android 5.1 and it works. I have tried to install version 3.0.0, but appcelerator does not even recognize it as module. Please anyone help, I cannot finish my app without admob.

**Comment by ashcoding** [comment]
@imlordeyaya Could you open a Jira ticket? http://jira.appcelerator.org/
